#!/bin/bash
#WTM_AUTO_SWITCH helper script, written by papampi
#Feel free to use, change, edit and do what you want with it.

source ~/1bash

BITCOIN="theGROUND"

# Creating a log file to record coin switch
LOG_FILE="/home/m1/8_wtmautoswitchlog"

if [ -e "$LOG_FILE" ] ; then
  #Limit the logfile, just keep the last 2K
#  LASTLOG=$(tail -n 2k  $LOG_FILE)
#  echo "$LASTLOG" 
#  echo ""
 echo "$(cat $LOG_FILE | grep switched | tail -n 2k)" > $LOG_FILE 

fi

while [ $BITCOIN == "theGROUND" ]
do

python2.7 '/home/m1/WTM_AUTO_SWITCH' /home/m1/WTM.json  | tee -a ${LOG_FILE}
sleep 5

CURRENT_COIN=$(head -n 200 /home/m1/1bash | grep COIN= | sed 's/COIN=//' | sed 's/\"//' | sed 's/\"//')
TOP_COIN=$(cat WTM_top_coin | grep : | sed 's/:[0-9][0-9]//' | sed 's/[0-9]//')
#TOP_COIN=$(cat /home/m1/top_coin)
TIMEIN=$WTM_AUTO_SWITCH_SYNC_INTERVAL
TIMEOUT=$(($TIMEIN * 60))
if [ "$CURRENT_COIN" != "$TOP_COIN" ]
then 
sed -i 's/'COIN=\"$CURRENT_COIN\"'/'COIN=\"$TOP_COIN\"/'' /home/m1/1bash
cat ~/WTM_current_revenue | grep `cat ~/WTM_top_coin | awk -F: '{print $1}'` | awk -F: '{print $2}' >> ~/WTM_24H_REV
SYNC_COUNT=$((`expr 1440 / $WTM_AUTO_SWITCH_SYNC_INTERVAL`))
echo "$(tail -$SYNC_COUNT WTM_24H_REV)" > WTM_24H_REV 
sed -i '/^$/d' WTM_24H_REV
sleep 1


sleep 1
pkill -e screen
pkill -f 3main

echo ""
echo "$(date) Mining switched from $CURRENT_COIN to $TOP_COIN" | tee -a ${LOG_FILE}
echo "Check again in $TIMEOUT seconds" #| tee -a ${LOG_FILE}
sleep $TIMEOUT
else

echo ""
echo "$(date) Same Coin on Top, Continue mining $CURRENT_COIN"  # | tee -a ${LOG_FILE}
echo ""
echo "Check again in $TIMEOUT seconds" #| tee -a ${LOG_FILE}
cat ~/WTM_current_revenue | grep `cat ~/WTM_top_coin | awk -F: '{print $1}'` | awk -F: '{print $2}' >> ~/WTM_24H_REV
SYNC_COUNT=$((`expr 1440 / $WTM_AUTO_SWITCH_SYNC_INTERVAL`))
echo "$(tail -$SYNC_COUNT WTM_24H_REV)" > WTM_24H_REV 
sed -i '/^$/d' WTM_24H_REV
sleep $TIMEOUT
fi
done








